general {
    hide_cursor = true
    grace = 0
    disable_loading_bar = false
}

background {
    monitor =
    path = /home/eya/.config/wallpapers/tokyo.jpg
    blur_passes = 2
    blur_size = 5
    brightness = 0.6
}

# Hora grande
label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = JetBrainsMono Nerd Font
    color = rgba(240, 230, 224, 1.0)
    position = 0, 200
    halign = center
    valign = center
}

# Fecha
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d de %B"
    font_size = 22
    font_family = JetBrainsMono Nerd Font
    color = rgba(201, 168, 212, 1.0)
    position = 0, 90
    halign = center
    valign = center
}

# Saludo con nombre de usuario
label {
    monitor =
    text = Hola, $USER
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    color = rgba(232, 184, 138, 1.0)
    position = 0, -50
    halign = center
    valign = center
}

# Campo de contraseña
input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(201, 168, 212, 1.0)
    inner_color = rgba(26, 22, 34, 0.8)
    font_color = rgba(240, 230, 224, 1.0)
    fade_on_empty = false
    placeholder_text = <i>Contraseña...</i>
    hide_input = false
    check_color = rgba(232, 184, 138, 1.0)
    fail_color = rgba(212, 122, 154, 1.0)
    fail_text = <i>Incorrecta</i>
    position = 0, -130
    halign = center
    valign = center
}
